CREATE DATABASE QLSV;
GO
USE QLSV;
GO

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN 
(
    MaSinhVien INT PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    DiaChi NVARCHAR(200),
    Email NVARCHAR(360)
);

-- Tạo bảng GIANGVIEN
CREATE TABLE GIANGVIEN 
(
    MaGiangVien INT PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    ChuyenNganh NVARCHAR(100),
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    DiaChi NVARCHAR(200),
    Email NVARCHAR(360)
);

-- Tạo bảng LOPHOC
CREATE TABLE LOPHOC 
(
    MaLop INT PRIMARY KEY,
    TenLop NVARCHAR(100) NOT NULL
);

-- Tạo bảng DANHSACHLOP
CREATE TABLE DANHSACHLOP (
    MaSinhVien INT,
    MaLop INT,
    PRIMARY KEY (MaSinhVien, MaLop)
);

-- Tạo bảng LOPHOC_GIANGVIEN
CREATE TABLE LOPHOC_GIANGVIEN (
    MaLop INT,
    MaGiangVien INT,
    PRIMARY KEY (MaLop, MaGiangVien)
);

-- Tạo bảng MONHOC
CREATE TABLE MONHOC (
    MaMonHoc INT PRIMARY KEY,
    TenMonHoc NVARCHAR(100) NOT NULL,
    SoTinChi INT NOT NULL
);

-- Tạo bảng LOPHOC_MONHOC
CREATE TABLE LOPHOC_MONHOC (
    MaLop INT,
    MaMonHoc INT,
    PRIMARY KEY (MaLop, MaMonHoc)
);

-- Tạo bảng GIANGVIEN_MONHOC
CREATE TABLE GIANGVIEN_MONHOC (
    MaGiangVien INT,
    MaMonHoc INT,
    PRIMARY KEY (MaGiangVien, MaMonHoc)
);

CREATE TABLE SINHVIEN 
(
    MaSinhVien INT PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    DiaChi NVARCHAR(200),
    Email NVARCHAR(360)
);

-- Tạo rằng buộc cho các bảng
ALTER TABLE SINHVIEN
ADD CONSTRAINT UQ_EmailSinhVien UNIQUE (Email);

ALTER TABLE GIANGVIEN
ADD CONSTRAINT UQ_EmailGiangVien UNIQUE (Email);

ALTER TABLE DANHSACHLOP
ADD CONSTRAINT FK_DanhSachLop_SinhVien FOREIGN KEY (MaSinhVien) REFERENCES SINHVIEN(MaSinhVien);
ALTER TABLE DANHSACHLOP
ADD CONSTRAINT FK_DanhSachLop_LopHoc FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop);

ALTER TABLE LOPHOC_GIANGVIEN
ADD CONSTRAINT FK_LopHocGiangVien_LopHoc FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop);
ALTER TABLE LOPHOC_GIANGVIEN
ADD CONSTRAINT FK_LopHocGiangVien_GiangVien FOREIGN KEY (MaGiangVien) REFERENCES GIANGVIEN(MaGiangVien);

ALTER TABLE LOPHOC_MONHOC
ADD CONSTRAINT FK_LopHocMonHoc_LopHoc FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop);
ALTER TABLE LOPHOC_MONHOC
ADD CONSTRAINT FK_LopHocMonHoc_MonHoc FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc);

ALTER TABLE GIANGVIEN_MONHOC
ADD CONSTRAINT FK_GiangVienMonHoc_GiangVien FOREIGN KEY (MaGiangVien) REFERENCES GIANGVIEN(MaGiangVien);
ALTER TABLE GIANGVIEN_MONHOC
ADD CONSTRAINT FK_GiangVienMonHoc_MonHoc FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc);
