-- Câu 1
SELECT nv.MANV
	 , CONCAT(nv.HONV, ' ', nv.TENLOT, ' ', nv.TENNV) AS HOTEN
	 , pb.MAPHG
	 , nv.NGSINH
	 , nv.PHAI
FROM dbo.NHANVIEN AS nv
INNER JOIN dbo.PHONGBAN AS pb ON nv.PHG = pb.MAPHG
WHERE pb.MAPHG = 4;

-- Câu 2
SELECT MANV
	 , CONCAT(HONV, ' ', TENLOT, ' ', TENNV) AS HOTEN
	 , NGSINH
	 , PHAI
	 , LUONG
FROM dbo.NHANVIEN
WHERE LUONG > 30000;

-- Câu 3
SELECT nv.MANV
	 , CONCAT(nv.HONV, ' ', nv.TENLOT, ' ', nv.TENNV) AS HOTEN
	 , pb.MAPHG
	 , nv.NGSINH
	 , nv.PHAI
	 , nv.LUONG
FROM dbo.NHANVIEN AS nv
INNER JOIN dbo.PHONGBAN AS pb ON nv.PHG = pb.MAPHG
WHERE (pb.MAPHG = 4 AND nv.LUONG > 25000) 
   OR (pb.MAPHG = 5 AND nv.LUONG > 30000);

-- Câu 4
SELECT MANV
	 , CONCAT(HONV, ' ', TENLOT, ' ', TENNV) AS HOTEN
	 , DCHI
FROM dbo.NHANVIEN
WHERE DCHI LIKE N'%TP Hcm%' OR DCHI LIKE N'%Tp Hồ Chí Minh';

-- Câu 5
SELECT MANV
	 , CONCAT(HONV, ' ', TENLOT, ' ', TENNV) AS HOTEN
FROM dbo.NHANVIEN
WHERE HONV LIKE 'N%';

--Câu 6
SELECT MANV
	 , CONCAT(HONV, ' ', TENLOT, ' ', TENNV) AS HOTEN
	 , FORMAT(NGSINH, 'dd-mm-yyyy') AS NGAYSINH
	 , DCHI
FROM dbo.NHANVIEN
WHERE CONCAT(HONV, ' ', TENLOT, ' ', TENNV) = N'Đinh  Bá  Tiên';