-- Bài 2:
USE QLDA;

-- B1
DECLARE @DAI FLOAT
	  , @RONG FLOAT
	  , @CHUVI FLOAT
	  , @DIENTICH FLOAT

SET @DAI = 30
SET @RONG = 20
SET @CHUVI = (@DAI + @RONG) * 2
SET @DIENTICH = @DAI * @RONG

PRINT 'Chu vi la: ' + CONVERT(CHAR(100), @CHUVI);
PRINT 'Dien tich la: ' + CONVERT(CHAR(100), @DIENTICH);

-- B2
DECLARE @MAX_LUONG FLOAT 
SET @MAX_LUONG = (
	SELECT MAX(LUONG) FROM NHANVIEN
);

SELECT *
FROM NHANVIEN
WHERE LUONG = @MAX_LUONG;

-- B3
DECLARE @AVG_LUONG FLOAT
SET @AVG_LUONG = (
	SELECT AVG(LUONG)
	FROM NHANVIEN 
);

SELECT HONV
	 , TENLOT
	 , TENNV
FROM NHANVIEN INNER JOIN PHONGBAN ON PHG = MAPHG
WHERE TENPHG LIKE N'Nghiên cứu' AND LUONG > @AVG_LUONG;

-- B4
DECLARE @SUB_TABLE TABLE (MAPB INT, TENPHONGBAN NVARCHAR(15), SOLUONGNHANVIEN INT, LUONGTRUNGBINH FLOAT)
INSERT INTO @SUB_TABLE 
	SELECT PHG
			, TENPHG
			, COUNT(MANV) 
			, AVG(LUONG)
	FROM NHANVIEN INNER JOIN PHONGBAN ON PHG = MAPHG
	GROUP BY PHG
			, TENPHG
	HAVING AVG(LUONG) > 30000
SELECT *
FROM @SUB_TABLE;

-- B5
DECLARE @SUB_TABLE2 TABLE (TENPHONGBAN NVARCHAR(15), SOLUONGDEAN INT)
INSERT INTO @SUB_TABLE
	SELECT TENPHG
		 , COUNT(MADA)
	FROM PHONGBAN INNER JOIN DEAN ON MAPHG = PHONG
	GROUP BY TENPHG
SELECT *
FROM @SUB_TABLE2
