USE QLDA;
GO

-- Câu 1
-- B1
CREATE FUNCTION FUNC_TINHTUOI(@MaNV CHAR(9))
RETURNS INT
AS
BEGIN
    DECLARE @Tuoi INT
    SELECT @Tuoi = DATEDIFF(YEAR, NGSINH, GETDATE())
    FROM NHANVIEN WHERE MaNV = @MaNV
    RETURN @Tuoi
END

GO

-- B2
CREATE FUNCTION FUNC_SOLUONGDEAN(@MaNV CHAR(9))
RETURNS INT
AS
BEGIN
    DECLARE @SoLuong INT
    SELECT @SoLuong = COUNT(*) 
    FROM PHANCONG WHERE MA_NVIEN = @MaNV
    RETURN @SoLuong
END

GO

-- B3
CREATE FUNCTION FUNC_DEMNHANVIENTHEOPHAIi(@Phai NVARCHAR(3))
RETURNS INT
AS
BEGIN
    DECLARE @SoLuong INT
    SELECT @SoLuong = COUNT(*) FROM NHANVIEN WHERE Phai = @Phai
    RETURN @SoLuong
END

GO

-- B4
CREATE FUNCTION FUNC_LUONGTRENTRUNGBINH(@TenPHG NVARCHAR(50))
RETURNS TABLE
AS
RETURN (
    SELECT HONV, TENLOT, TENNV, LUONG
    FROM NHANVIEN
    WHERE LUONG > (SELECT AVG(LUONG) FROM NHANVIEN WHERE PHG = 
        (SELECT MaPHG FROM PHONGBAN WHERE TenPHG = @TenPHG))
)

GO

-- B5
CREATE FUNCTION FUNC_THONGTINPHONG(@MaPHG INT)
RETURNS TABLE
AS
RETURN (
    SELECT pb.TenPHG, nv.HONV, nv.TENLOT, nv.TENNV, 
           (SELECT COUNT(*) FROM DEAN WHERE MaPHG = @MaPHG) AS SoLuongDeAn
    FROM PHONGBAN pb
    JOIN NHANVIEN nv ON pb.TRPHG = nv.MaNV
    WHERE pb.MaPHG = @MaPHG
)

GO

-- Câu 2
-- B1
CREATE VIEW VIEW_THONGTINNHANVIEN AS
SELECT NV.HONV, NV.TENNV, PB.TENPHG, DP.DIADIEM
FROM NHANVIEN NV
JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
JOIN DIADIEM_PHG DP ON PB.MAPHG = DP.MAPHG;

GO
-- B2
CREATE VIEW VIEW_TENLUONGTUOI AS
SELECT TENNV, LUONG, DATEDIFF(YEAR, NGSINH, GETDATE()) AS TUOI
FROM NHANVIEN;

GO
-- B3
CREATE VIEW VIEW_PHONGBANDONGNHANVIENNHAT AS
SELECT PB.TENPHG, NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS HO_TEN_TRUONG_PHONG
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
WHERE PB.MAPHG = (
    SELECT TOP 1 PHG
    FROM NHANVIEN
    GROUP BY PHG
    ORDER BY COUNT(*) DESC
);