USE QLDA;

-- Câu 1
-- B1
SELECT TenDA
	 , SUM(ThoiGian) AS TONGTHOIGIANLAMVIEC
FROM DEAN DA INNER JOIN CONGVIEC CV ON CV.MADA = DA.MADA
			 INNER JOIN PHANCONG PC ON PC.MADA = CV.MADA AND PC.STT = CV.STT
GROUP BY TenDA;

SELECT TenDA
	 , CAST(SUM(ThoiGian) AS DECIMAL(10,2)) AS TONGTHOIGIANLAMVIEC
FROM DEAN DA INNER JOIN CONGVIEC CV ON CV.MADA = DA.MADA
			 INNER JOIN PHANCONG PC ON PC.MADA = CV.MADA AND PC.STT = CV.STT
GROUP BY TenDA;

-- B2
SELECT MAPHG
	 , TENPHG
	 , AVG(LUONG) AS LUONGTRUNGBINH
FROM PHONGBAN PB INNER JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY MAPHG
	   , TENPHG;

SELECT MAPHG
	 , TENPHG
	 , CAST(AVG(LUONG) AS VARCHAR(10)) AS LUONGTRUNGBINH 
	 , LEFT(CAST(AVG(LUONG) AS VARCHAR(10)),3) + REPLACE(CAST(AVG(LUONG) AS VARCHAR(10)),LEFT(CAST(AVG(LUONG) AS VARCHAR(10)),3),',')
FROM PHONGBAN PB INNER JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY MAPHG
	   , TENPHG;

-- Câu 2
-- B1
SELECT TenDA
	 , SUM(ThoiGian) AS TONGTHOIGIANLAMVIEC
	 , CEILING(SUM(ThoiGian)) AS TONGTHOIGIANLAMVIEC_CEILING
FROM DEAN DA INNER JOIN CONGVIEC CV ON CV.MADA = DA.MADA
			 INNER JOIN PHANCONG PC ON PC.MADA = CV.MADA
GROUP BY TenDA;

SELECT TenDA
	 , SUM(ThoiGian) AS TONGTHOIGIANLAMVIEC
	 , FLOOR(SUM(ThoiGian)) AS TONGTHOIGIANLAMVIEC_FLOOR
FROM DEAN DA INNER JOIN CONGVIEC CV ON CV.MADA = DA.MADA
			 INNER JOIN PHANCONG PC ON PC.MADA = CV.MADA
GROUP BY TenDA;

SELECT TenDA
	 , SUM(ThoiGian) AS TONGTHOIGIANLAMVIEC
	 , ROUND(SUM(ThoiGian),2) AS TONGTHOIGIANLAMVIEC_ROUND
FROM DEAN DA INNER JOIN CONGVIEC CV ON CV.MADA = DA.MADA
			 INNER JOIN PHANCONG PC ON PC.MADA = CV.MADA
GROUP BY TenDA;
 
SELECT CONCAT(HONV, ' ', TENLOT, ' ', TENNV) AS HOTENNV
FROM NHANVIEN
WHERE LUONG >= (
				SELECT ROUND(AVG(LUONG),2)
				FROM NHANVIEN NV INNER JOIN PHONGBAN PB ON PB.MAPHG = NV.PHG
				WHERE TENPHG = N'Nghiên cứu'
);

-- Câu 3
-- B1
SELECT CONCAT(UPPER(HONV), ' ', TENLOT, ' ', TENNV) AS HOTEN FROM NHANVIEN NV
WHERE NV.MANV IN (
			SELECT MA_NVIEN FROM THANNHAN
			GROUP BY MA_NVIEN
			HAVING COUNT(MA_NVIEN) >= 2
);

-- B2
SELECT CONCAT(HONV, ' ', UPPER(TENLOT), ' ', TENNV) AS HOTEN FROM NHANVIEN NV
WHERE NV.MANV IN (
					SELECT MA_NVIEN FROM THANNHAN
					GROUP BY MA_NVIEN
					HAVING COUNT(MA_NVIEN) >= 2
);

-- B3
SELECT CONCAT(HONV, ' ', TENLOT, ' ', LOWER(LEFT(TENNV, 1)) 
									+ UPPER(SUBSTRING(TENNV, 2, 1)) 
									+ UPPER(SUBSTRING(TENNV, 3,LEN(TENNV)))) AS HOTEN 
FROM NHANVIEN

-- B4
SELECT 
    DCHI,
    LTRIM(RTRIM(SUBSTRING(DCHI, CHARINDEX(',', DCHI) + 1, 
        CHARINDEX(',', DCHI + ',', CHARINDEX(',', DCHI) + 1) - CHARINDEX(',', DCHI) - 1))) AS TenDuong
FROM NHANVIEN;

-- Câu 3
-- B1
SELECT * FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965;

-- B2
SELECT MANV
	 , CONCAT(HONV, ' ', TENLOT, ' ', TENNV)
	 , YEAR(GETDATE()) - YEAR(NGSINH) AS TUOI
FROM NHANVIEN;

-- B3
SELECT MANV
	 , CONCAT(HONV, ' ', TENLOT, ' ', TENNV)
	 , DATENAME(WEEKDAY, NGSINH) AS THUSINH
FROM NHANVIEN;

-- B4
SELECT COUNT(NV.MANV) AS SOLUONGNHANVIEN
	 , CONCAT(NV.HONV, ' ', NV.TENLOT, ' ', NV.TENNV) AS TENTRUONGPHONG
	 , FORMAT(PB.NG_NHANCHUC, 'dd-MM-yy') AS NGAYNHANCHUC
FROM NHANVIEN NV INNER JOIN PHONGBAN PB ON NV.MA_NQL = PB.MAPHG
WHERE PB.NG_NHANCHUC IS NOT NULL
GROUP BY NV.HONV
	   , NV.TENLOT
	   , NV.TENNV
	   , PB.NG_NHANCHUC;