USE QLDA;
GO

-- Câu 1
-- B1
CREATE TRIGGER TRIG_CHECK_INPUT_LUONG ON NHANVIEN
FOR INSERT 
AS 
	IF (SELECT LUONG FROM NHANVIEN) <= 15000
		BEGIN
			PRINT('Lương phải > 15000')
			ROLLBACK TRANSACTION
		END

GO

-- B2
CREATE TRIGGER TRIG_CHECK_INPUT_TUOI ON NHANVIEN
FOR INSERT 
AS	
	DECLARE @TUOI INT;
	SET @TUOI = YEAR(GETDATE()) - (SELECT YEAR(NGSINH) FROM NHANVIEN)
	IF (@TUOI < 18 OR @TUOI > 65)
		BEGIN
			PRINT('Lương phải > 15000')
			ROLLBACK TRANSACTION
		END

GO

-- B3
CREATE TRIGGER TRIG_CHECK_UPDATE_DIACHI ON NHANVIEN
FOR UPDATE 
AS 
	IF (SELECT DCHI FROM NHANVIEN) LIKE '%TP HCM'
		BEGIN
			PRINT('Không thể UPDATE nhân viên có địa chỉ ở TP HCM')
			ROLLBACK TRANSACTION
		END

GO

-- Câu 2
-- B1
CREATE TRIGGER TRIG_AFTER_INSERT_TONGNHANVIENNAMVANU ON NHANVIEN
AFTER INSERT 
AS
	BEGIN
		DECLARE @COUNT_NVIEN_NAM INT;
		DECLARE @COUNT_NVIEN_NU INT;
		SELECT @COUNT_NVIEN_NAM = COUNT(*) FROM NHANVIEN WHERE PHAI LIKE 'Nam'
		SELECT @COUNT_NVIEN_NU = COUNT(*) FROM NHANVIEN WHERE PHAI LIKE N'Nữ'
		PRINT N'Số lương nhân viên Nam = ' + @COUNT_NVIEN_NAM + N' Nữ = ' + @COUNT_NVIEN_NU
	END

GO

-- B2
CREATE TRIGGER TRIG_AFTER_UPDATE_TONGNHANVIENNAMVANU ON NHANVIEN
AFTER UPDATE 
AS
	BEGIN
		DECLARE @COUNT_NVIEN_NAM INT;
		DECLARE @COUNT_NVIEN_NU INT;
		SELECT @COUNT_NVIEN_NAM = COUNT(*) FROM NHANVIEN WHERE PHAI LIKE 'Nam'
		SELECT @COUNT_NVIEN_NU = COUNT(*) FROM NHANVIEN WHERE PHAI LIKE N'Nữ'
		PRINT N'Số lương nhân viên Nam = ' + @COUNT_NVIEN_NAM + N' Nữ = ' + @COUNT_NVIEN_NU
	END

GO

-- B3
CREATE TRIGGER TRIG_AFTER_DELETE_TONGSOLUONGDEANCUAMOINHANVIEN ON NHANVIEN
AFTER DELETE 
AS 
	BEGIN
		SELECT MA_NVIEN, COUNT(MADA) FROM PHANCONG
		GROUP BY MA_NVIEN
	END

GO

-- Câu 3
-- B1
CREATE TRIGGER TRIG_INSTEADOF_DELETE_XOATHANNHANLIENQUAN ON NHANVIEN
INSTEAD OF DELETE
AS
	BEGIN
		DELETE FROM THANNHAN WHERE MA_NVIEN IN
		(SELECT MA_NVIEN FROM deleted)
		DELETE FROM NHANVIEN WHERE MANV IN
		(SELECT MANV FROM deleted)
	END

GO

-- B2
CREATE TRIGGER TRIG_INSTEADOF_INSERT_THEMNHANVIENMOI ON NHANVIEN
INSTEAD OF INSERT
AS
	BEGIN
		INSERT INTO PHANCONG VALUES((SELECT MANV FROM inserted ), 1, 1, 10)
	END

GO

